### ISSUE TITLE
x-xz-compressed-tar is not supported

### ISSUE THREAD

**Issue by pmiess** [0install/0install-win#101]
Using the Zero Install Feed Editor,
in an archive element I selected a xz compressed tar file and selected application/x-xz-compressed-tar as the MIME type

I pushed "Add missing" button
The archive was downloaded and an error message box was displayed
"The archive MIME type 'application/x-xz-commpressed-tar' is not supported."
archive http://win-builds.org/1.5.0/packages/windows_32/SDL2-2.0.3-1-i686-w64-mingw32.txz

Zero Install Publishing Tools version 2.10

**Comment by bastianeicher** [comment]
Thanks for the feedback. I looked around for a .NET XZ-compression library and found [XZ.NET](https://github.com/RomanBelkov/XZ.NET). I integrated it in Zero Install in commit a0cece2. The initial unit tests are passing and the archive you mentioned works. If everything remains stable this will be in version 2.11 of Zero Install and the Publishing Tools, to be released some time next week.

**Comment by bastianeicher** [comment]
Zero Install 2.11 and the accompanying Zero Install Publishing Tools have been released with support for `.tar.xz` archives.
