### ISSUE TITLE
Zero install tools cant download  terraform

### ISSUE THREAD

**Issue by pmiess** [0install/0install-win#104]
When I put the URL https://releases.hashicorp.com/terraform/0.9.5/terraform_0.9.5_windows_amd64.zip
into the Zero install tools wizard a message dialogue is displayed that says "Failed to download"
with part of the URL.

Evironment is modern.ie VM for windows 7 IE 11. running on KVM and installing critical windows updates as well as the optional dot-net 4.5.2 update. Without 4.5.2 zero install will not run.
IE 11 can download the file from that VM.

**Comment by bastianeicher** [comment]
Thanks for reporting this. I have been able to reproduce your issue and will look into it.

**Comment by bastianeicher** [comment]
Fixed in b3ce965. I will release a new build soon and notify you here.

**Comment by bastianeicher** [comment]
Zero Install Publishing Tools 2.13.1 have been released which include this fix.
