### ISSUE TITLE
Powershell runner fails

### ISSUE THREAD

**Issue by pmiess** [0install/0install-win#111]
I created this feed https://pmiess.gitlab.io/0install-feeds/systools.xml
It has power shell scripts that 0publish automatically sets the runner for but if I run the command the runner feed cant be found.
This is the error
"Can't find all required implementations:
- http://repo.roscidus.com/powershell/powershell -> (problem)
    Main feed 'http://repo.roscidus.com/powershell/powershell' not available
    No known implementations at all
- https://pmiess.gitlab.io/0install-feeds/systools.xml -> 1.10 (x86)"

**Comment by bastianeicher** [comment]
Support for detecting PowerShell as a "native" package in Zero Install for Windows has not been implemented yet.

This should be relatively easy to add. Will keep you informed.

**Comment by bastianeicher** [comment]
This pull request creates the missing PowerShell feed: 0install/repo.roscidus.com#50

This commit adds support for detecting Windows PowerShell via a `<package-implementation>` as used used in the feed: 0install/0install-dotnet@fa00b94

I will post here once these are released and ready to be used.

**Comment by bastianeicher** [comment]
The pull request has been merged and Zero Install for Windows 2.14.5 has been released.

Seems to be working fine now:

    > 0install run --command=EchoArgs https://pmiess.gitlab.io/0install-feeds/systools.xml test
    Arg1 = test
