### ISSUE TITLE
Feed publishing : Microsoft office

### ISSUE THREAD

**Issue by limbo127** [0install/0install-win#112]
Hello, 
we are trying to use 0install to start microsoft office without succes
How can we preceed ? 
1 - from install file, there's just a setup.exe find
2 - from rezip an office install, then choose winword or excel , does not work , nothing start 

regards, 
Nicolas

**Comment by bastianeicher** [comment]
Hi Nicolas,

thank you for your interest in Zero Install.

Zero Install is designed to run applications without any side effects. It does this by extracting each version of an app and each of its dependencies in separate directories and connecting them via environment variables at startup.

This works well with many popular applications. However, some applications like Microsoft Office have a much more complex installation process, requiring a number of registry entries, shared DLLs installed in system directories, etc.. Zero Install cannot handle this kind of application out-of-the-box.

One way to work around this, is to use tools like [VMware ThinApp](https://en.wikipedia.org/wiki/VMware_ThinApp) or [Microsoft App-V](https://en.wikipedia.org/wiki/Microsoft_App-V) to virtualize an application's interaction with the operation system and turn it into a standalone file. This can then easily be distributed with Zero Install or other deployment solutions. However, these tools are all commercial and somewhat expensive.

If using LibreOffice instead is a viable option for you, there is already a [Zero Install feed for LibreOffice](http://0install.de/feeds/LibreOffice.xml) available.

Regards
Bastian

**Comment by limbo127** [comment]
Ok, 
but why is it possible with Chocolatey ?  in product comparaison there's nothing about application compatible difference
Regards, 
Nicolas

**Comment by bastianeicher** [comment]
Chocolatey packages usually just download and execute an application's original installer. This means there are no restrictions on the kinds of things it can install. On the flip side it cannot provide features like side-by-side installs and auto-updates unless the app provides them by itself.

Zero Install on the other hand intentionally limits the package "installation" process to extracting an archive (plus dependency injection) and offers desktop integration (start menu entries, file assocs, etc.) as an optional step. This gives the use more control but excludes some apps.

Regarding the [Product Comparison page](https://0install.de/about/product-comparison/), one would have to consider MS Office part of the category "system tools and frameworks". But thanks for the hint, I'll try to make the table more clear.

**Comment by limbo127** [comment]
ok,
thanks for this explanation
regards,
nicolas

2018-03-02 7:30 GMT+01:00 Bastian Eicher <notifications@github.com>:
