### ISSUE TITLE
0install external solver fails to download from gitlab.io pages

### ISSUE THREAD

**Issue by pmiess** [0install/0install-win#113]
If 0install falls back on the external solver it cant download from gitlab.io
with verbose flag the error is 

External solver: Curl error: The requested URL returned error: 404 Not Found: Curl.CurlException(_)
External solver:feed https://pmiess.gitlab.io/0install-feeds/gnuwin32/gettext.xml: Error downloading 'https://pmiess.gitlab.io/0install-feeds/gnuwin32/gettext.xml': SSL certificate problem: unable to get local issuer certificate

example feed 0install -v run --command=gifburst https://pmiess.gitlab.io/0install-feeds/gnuwin32/giflib.xml

**Comment by bastianeicher** [comment]
Zero Install for Windows uses the OCaml version of Zero Install as an external solver. Moving this issue to 0install/0install#81, where the OCaml version is maintained.
