### ISSUE TITLE
0install external solver doesnt like gentoo package names

### ISSUE THREAD

**Issue by pmiess** [0install/0install-win#114]
if 0install falls back on the external solver it complains about Gentoo package names that contain /

External solver: Ignoring invalid distribution package name 'sys-devl/gettext'

example feed 0install -v run --command=gifburst https://pmiess.gitlab.io/0install-feeds/gnuwin32/giflib.xml

**Comment by bastianeicher** [comment]
Zero Install for Windows uses the OCaml version of Zero Install as an external solver. Moving this issue to 0install/0install#80, where the OCaml version is maintained.
