### ISSUE TITLE
Cant download  gitlab.io feeds

### ISSUE THREAD

**Issue by pmiess** [0install/0install-win#118]
When accessing gitlab.io feeds 0install fails to connect, 
Internet Explorer also fails to connect. 
Firefox can load the feeds on the same system.
Here is a log of an attempt.
```
C:\Users\x86Tester>0install run https://pmiess.gitlab.io/0install-feeds/perl.xml
``
Downloading https://pmiess.gitlab.io/0install-feeds/perl.xml...
[                    ] Web error
Error while downloading feed 'https://pmiess.gitlab.io/0install-feeds/perl.xml'.
 Trying feed mirror server
Downloading http://roscidus.com/0mirror/feeds/https/pmiess.gitlab.io/0install-fe
eds%23perl.xml/latest.xml...
[                    ] Web error
Failed to download https://pmiess.gitlab.io/0install-feeds/perl.xml.
        The request was aborted: Could not create SSL/TLS secure channel.
Running external solver...
[                    ]
Can't find all required implementations:
        - https://pmiess.gitlab.io/0install-feeds/perl.xml -> (problem)
            Main feed 'https://pmiess.gitlab.io/0install-feeds/perl.xml' not available
            No known implementations at all
```

**Comment by bastianeicher** [comment]
GitHub require TLS 1.2.

Zero Install for Windows' support for various SSL/TLS versions depends on the installed version of the .NET Framework.

.NET Framework 4.5 (included in Windows 8+) added support for TLS 1.2. Older versions of the .NET Framework can also get TLS 1.2 support via OS-specific updates (e.g., [KB3154518](https://support.microsoft.com/kb/3154518) for Windows 7). These are usually automatically installed via Windows Update.

Which version of Windows and/or .NET Framework are you running?

**Comment by pmiess** [comment]
Windows 7 with all the important updates and .net 4.7.2 installed installed.

**Comment by bastianeicher** [comment]
Hmm, it seems TLS 1.2 support [needs to be explicitly enabled on Windows 7](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#support-for-tls-12).

According to [Microsoft documentation](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings#tls-12), you should be able to do that with the following command-line:

    reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server" /f /v Enabled /t REG_DWORD /d 1

Zero Install already [displays a warning](https://github.com/nano-byte/common/blob/9024e2963d171e0d0d3fb28f542704bbfe495cb3/src/Common/Net/NetUtils.cs#L59) when running on a .NET Version that does not support TLS 1.2. I suppose I should also check for and warn about this registry key.

**Comment by pmiess** [comment]
I dont think this is it, I can access gitlab.com so its not TLS 1.2

**Comment by pmiess** [comment]
I tried it anyway and it didnt help

**Comment by bastianeicher** [comment]
This works fine on my Windows 10 machine by the way:

    0install run https://pmiess.gitlab.io/0install-feeds/perl.xml

The only remaining difference between `gitlab.com` and `pmiess.gitlab.io` I can think of is the certificate issuer: "Sectigo RSA Domain Validation Secure Server CA" vs "AlphaSSL CA - SHA256 - G2"

Since you mentioned Internet Explorer also isn't working, I'd guess something must be missing from the Windows Certificate Store.

**Comment by pmiess** [comment]
I've imported the AlphaSSL CA certificate as a trusted intermediate certificate and verified that it and its parent are in windows certificate share. Still doesn't work. 
I'm going to rewrite my feeds to use the raw file path to work around this problem. 

I guess this is probably not related to zero install so we should probably close this
