### ISSUE TITLE
Newbie-friendly name for 0publish-win menu item

### ISSUE THREAD

**Issue by akavel** [0install/0install-win#121]
As a newbie user, when trying to find how to create a new app/package in 0install via GUI, it didn't occur to me that the "Publish a feed" option in the menu is what I need. I'm not yet used to the name "feed", and also "publish" is actually a later act in my mind (where I'd actually put the feed on some website; 0publish doesn't do this for me); I would find it really cool if this menu item could be named "Wrap a new package", or maybe "Create a feed for a new package", or otherwise something expressed in somewhat more "typical" terms, easier to understand for a newbie.

**Comment by bastianeicher** [comment]
Hi @akavel, thanks for the suggestion. You're righht, the term "package" is definitely easier to place for first-time users that "feed". I think I'll rename the menu item to "Create a new package" in the next release.
