### ISSUE TITLE
colon in package name prevents integration

### ISSUE THREAD

**Issue by pmiess** [0install/0install-win#122]
If you create a package whose name is Parallel::ForkManager integration fails with a stack track
[stacktrace.txt](https://github.com/0install/0install-win/files/3993240/stacktrace.txt)

The message "The given path's format is not supported" does not make the problem clear. 
A better message or creating a path without colons would be nice.

**Comment by bastianeicher** [comment]
Thanks for reporting this. I think I'll need to make two changes:

- When auto-generating shortcut names for desktop integration Zero Install should automatically replace any characters that are not valid in file names on Windows.
- When generating shortcuts potentially still invalid filenames (e.g. manually entered by a user) should produce a nice error message and not result in a crash with a stack trace.

**Comment by bastianeicher** [comment]
Fixed in 0install/0install-dotnet@4d0ae0d
