### ISSUE TITLE
"The system cannot find the file specified"

### ISSUE THREAD

**Issue by VladPutinEu** [0install/0install-win#139]
When I try to install the "GitHub CLI" it shows an error window, "The system cannot find the file specified."
https://user-images.githubusercontent.com/57074714/103099873-07670d00-45c5-11eb-9748-f8179a79ef48.png

When I try to install "GitVersion" it just shows a command prompt which quickly closes. I see nothing installed in my system.

When I try to install ".NET Core Runtime" it says it's installing and then it says "Completed" but I see nothing under "My applications."

**Comment by bastianeicher** [comment]
Thanks for reporting these issues.

The problem with GitHub CLI is now fixed (0install/apps@e94a7dd9278b8521f09dfc67f7ff754e92f53793). Please try clicking on the dropdown next to the "Run" button and selecting "Update".

All of the apps you tried are command-line tools. Running them from the GUI without command-line arguments will open a terminal window, show some output and then vanish again. Just like when you double-click on a command-line EXE in Explorer.

To install/integrate these apps, click on the "star" button below the "Run" button twice and then choose OK. You can then run these apps from the command-line.

![0install-integrate](https://user-images.githubusercontent.com/414366/103101630-d31d3c00-4618-11eb-8e66-c4152d3c29a9.gif)

**Comment by VladPutinEu** [comment]
Thanks for the help. But how do I uninstall an application?

**Comment by bastianeicher** [comment]
Click on the drop-down next to the "Star" icon and select "Remove".

Note that all these operations can also be performed via the command-line: https://docs.0install.net/details/cli/

**Comment by VladPutinEu** [comment]
Does that just remove the integrations or does it completely remove the application and its files?

**Comment by bastianeicher** [comment]
Zero Install never really "installs" an app. When you run an app for the first time it is downloaded and extracted to a [cache](https://docs.0install.net/details/cache/) and run from there.

Integrations (like a command-line aliases) are just shortcuts for running a command like `0install run https://apps.0install.net/devel/gitversion.xml`. After removing integrations the apps stay in the cache in case you want to run them again.

To remove an app from the cache click on "Tools" in the menu at the bottom and then "Cache management".

**Comment by VladPutinEu** [comment]
I really appreciate your product and what you're trying to do. But I really think you should work on making 0install more user-friendly. It's really hard to understand at first and takes a while to grasp.
