### ISSUE TITLE
keyword search broken

### ISSUE THREAD

**Issue by pmiess** [0install/0install-win#142]
If you open the keyword search dialog in the latest version and type a search nothing is returned, even if there is something that should match and command line search returns results for it

**Comment by bastianeicher** [comment]
This has already been fixed in e95fc623cf221e61d1d38dfaf04d4420ff99e14f, however it's not in a released version yet. I'll post in this ticket as soon as an update is released.

**Comment by bastianeicher** [comment]
[Zero Install for Windows 2.18.7](https://github.com/0install/0install-win/releases/tag/2.18.7) has been released with this fix.
