### ISSUE TITLE
Does portable mode modify the system?

### ISSUE THREAD

**Issue by VladPutinEu** [0install/0install-win#144]
When using ZeroInstall in portable mode will all the programs be portable and work off the thumb-drive, making no changes to the system?

**Comment by bastianeicher** [comment]
In [portable mode](https://docs.0install.net/details/windows/#portable-mode) Zero Install itself, its settings and the apps it downloads are all stored on the thumb-drive. Features that would modify the system (e.g., desktop integration) are not available.

However, applications launched by Zero Install are not automatically made portable by this. They will store config in their usual location (e.g., registry or `%appdata%`).

**Comment by VladPutinEu** [comment]
> In [portable mode](https://docs.0install.net/details/windows/#portable-mode) Zero Install itself, its settings and the apps it downloads are all stored on the thumb-drive. Features that would modify the system (e.g., desktop integration) are not available.
> 
> However, applications launched by Zero Install are not automatically made portable by this. They will store config in their usual location (e.g., registry or `%appdata%`).

@bastianeicher So the programs aren't completely portable like PortableApps.com?

**Comment by bastianeicher** [comment]
That's right.
