### ISSUE TITLE
hash of sed package changed 

### ISSUE THREAD

**Issue by pmiess** [0install/0install-win#145]
the hash for the sed gnuwin32 package changed 
https://github.com/0install/apps/blob/master/utils/sed.xml
I ran old versions of 0publish win and created the hash in them
in 2.16.7 the hash is created as currently in the repo.
in 2.17.3 it creates a new hash.

**Comment by bastianeicher** [comment]
Thanks for reporting the broken feed. I've updated it with the new hash / manifest digest.

The Linux version of 0install uses command-line tools like `unzip` or `tar` to extract archives. The Windows version on the other hand uses in-process libraries like [SharpZipLib](https://github.com/icsharpcode/SharpZipLib) to allow for progress bars and easier deployment.

In most cases both extraction methods produce identical results. Unfortunately the ZIP standard is a little imprecise when it comes to things like timestamps. There are many ways a file's "last changed" value can be stored in a ZIP archive (DOS time, Unix time, NTFS time, etc.). I've made an effort to ensure Zero Install for Windows treats these exactly the same as `unzip` on Linux to ensure manifest digests match across platforms. Unfortunately I missed a few corner cases, which led to timestamps and therefore [manifest digests](https://docs.0install.net/specifications/manifest/) to change when I fixed them (e.g., by contributing PRs back to SharpZipLib).

So the old manifest digest would have led to an error message if you ran something like `0install download --os=Windows https://apps.0install.net/utils/sed.xml` on Linux. The new manifest digest should work for current versions of 0install on all platforms.

**Comment by pmiess** [comment]
@bastianeicher  I thought that 2.16.7 (Jul 25, 2019) was after the changes you made to fix this timestamp problem which we were discussing as having already been made in May here https://github.com/0install/apps/pull/113.

**Comment by bastianeicher** [comment]
Unfortunately there were multiple such issues, each affecting only a certain subset of ZIP archives. The last change to the ZIP extraction logic occurred in 2.17.0. I added a note about this to the [release notes](https://github.com/0install/0install-dotnet/releases/tag/2.17.0).
