### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by Texxer** [0install/0install-win#173]
Hi

There is no mention of any Uninstall function for 0install in the Docs.

I found these folders:

C:\Users\X\AppData\Roaming\Programs\Zero Install
C:\Users\X\AppData\Roaming\0install.net

But there are also various entries in the Windows Registry...

**Comment by bastianeicher** [comment]
Hi @Texxer,

when Zero Install for Windows is [installed/deployed explicitly](https://docs.0install.net/details/windows/#deployment) an uninstall entry is created in the usual Windows "Apps and Features" list.

However, when Zero Install for Windows is installed/deployed implicitly as a dependency of another app (we call this "library mode") it does not show up in the "Apps and Features" list. In this case it is automatically removed when the app that uses it is uninstalled.

Independently of this, you can always use the command [0install self remove](https://docs.0install.net/details/cli/#self-remove) to uninstall Zero Install. For example:

```powershell
& "$env:appdata\Programs\Zero Install\0install-win.exe" self remove
```
