### ISSUE TITLE
Update Links to SignPath

### ISSUE THREAD

**Issue by SabotageAndi** [0install/0install-win#189]
Hi!
I am the Developer Evangelist of SignPath.

Could you change the notice about us from

    This program uses free code signing provided by [SignPath.io](https://signpath.io/) and a certificate by the [SignPath Foundation](https://signpath.org/).

to

    This program uses free code signing provided by [SignPath.io](https://signpath.io?utm_source=foundation&utm_medium=github&utm_campaign=0install), and a certificate by the [SignPath Foundation](https://signpath.org?utm_source=foundation&utm_medium=github&utm_campaign=0install)

Thanks!

**Comment by bastianeicher** [comment]
Sure thing, changed. :)
