### ISSUE TITLE
How to preserve the signing key?

### ISSUE THREAD

**Issue by sparksh** [0install/0install-win#193]
I created a few feeds to learn about 0install and subsequently moved to a new computer. I preserved the hard disk from the old machine but it's no longer bootable. Is there a way I can fetch the signing key from the old disk so I can continue with the same key on my new computer? (Some files to copy or keys to pull out of the old registry?) 

Thanks.

**Comment by bastianeicher** [comment]
0install internally uses GnuPG for signing feeds. It stores its keys in `C:\Users\[USERNAME]\AppData\Roaming\gnupg`. Copying those to your new machine should do the trick.

**Comment by sparksh** [comment]
It works -
Thanks very much!
