### ISSUE TITLE
0install was installed on my computer without permission how do I delete it

### ISSUE THREAD

**Issue by hwalil00** [0install/0install-win#196]
0install was installed on my computer without permission how do I delete it
![image](https://github.com/0install/0install-win/assets/146012083/64ca03ad-935b-4028-94c0-44a6fb041d4e)

**Comment by bastianeicher** [comment]
0install may be installed as a dependency of another application, for example DeepL, for use as an updater. When uninstalling that app 0install will automatically be removed too.

Alternatively you can run:

```
"%appdata%\Programs\Zero Install\0install-win.exe" self remove
```
