### ISSUE TITLE
Portable version on website still 2.25.1.0

### ISSUE THREAD

**Issue by JohnLGalt** [0install/0install-win#198]
Hi, there,

Just a couple of quick questions: 

1. Does it usually take a few days for the portable version to propagate to the website?
2. Would you consider adding the portable version here to this repo?

I apologize if this was already covered, but I searched the Issues list for portable and only found 3 closed issues, none dealing with availability.

**Comment by bastianeicher** [comment]
Hi @JohnLGalt,

the portable and regular versions of Zero Install use the same update mechanism, so new versions become available at the same time.

You are probably referring to `zero-install.exe`, which is missing in [Release 2.15.2](https://github.com/0install/0install-win/releases/tag/2.25.2). Please note that this is only the [Bootstrapper](https://docs.0install.net/details/windows/#bootstrapper), which is usually but not always updated together with Zero Install itself.

You can always get the latest available version of the Bootstrapper (2.15.1 at the moment) from https://get.0install.net/zero-install.exe. Running this will automatically download and run the latest available version of Zero Install (2.15.2 at the moment).

All this is independent from the [Portable Mode](https://docs.0install.net/details/windows/#portable-mode), which allows you to configure Zero Install to put all its files in a single directory, e.g., for use on a USB thumb drive.

Hope this helps.

Regards
Bastian

**Comment by JohnLGalt** [comment]
Ahh, yes, I grab the .ZIP version, and it has only the three files, and the executable still shows at 2.25.1.0.

Thanks for the explanation, and sorry for the misunderstanding.

**Comment by yaoyingkeji** [comment]
> Ahh, yes, I grab the .ZIP version, and it has only the three files, and the executable still shows at 2.25.1.0.
> 
> Thanks for the explanation, and sorry for the misunderstanding.

Yes, when we extract attachments to local disk, the modification time of the file is changed
