### ISSUE TITLE
0capture prints NotImplementedException when using --collect-files command line flag

### ISSUE THREAD

**Issue by philip-miess** [0install/0install-win#92]
When the “--collect-files” command line flag was included, a new error was output.

C:\temp\docfetcher>0capture start dockfetcher.snapshot
<ran installer>
C:\temp\docfetcher>0capture finish dockfetcher.snapshot docfetcher.xml --installation-dir="C:\Program Files (x86)\DocFetcher" --main-exe=DocFetcher.exe --collect-files
Searching for executable files...
[====================] Complete

Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.
   at ZeroInstall.Capture.Cli.CaptureCommand.Finish()
   at ZeroInstall.Capture.Cli.Program.Main(String[] args)

**Comment by bastianeicher** [comment]
Thank you for the bug report. :)
This is now fixed in Zero Install Publishing Tools 2.8.2.
